copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_BaseLib.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_BaseSafe.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_Algorithm.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_Core.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_ManagePool.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\Cryption.dll" "./"

copy /y "D:\XEngine\XEngine_SourceCode\Debug\XClient_APIHelp.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XClient_Stream.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XClient_Socket.dll" "./"

copy /y "D:\XEngine\XEngine_SourceCode\Debug\NetHelp_XSocket.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\NetHelp_APIAddr.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\NetHelp_APIHelp.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_SystemApi.dll" "./"

copy /y "D:\XEngine\XEngine_SourceCode\Debug\HelpComponents_DataBase.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\HelpComponents_XLog.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\RfcComponents_HttpProtocol.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\RfcComponents_NatProtocol.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\RfcComponents_NTPProtocol.dll" "./"

copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_AVHelp.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_VideoCodec.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_AudioCodec.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_AVCollect.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_AVCodec\avcodec-60.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avdevice-60.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avfilter-9.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avformat-60.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avutil-58.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\swresample-4.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\swscale-7.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\postproc-57.dll" "./"