copy /y "%XEngine_Lib32%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_BaseLib\XEngine_BaseSafe.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_BaseLib\XEngine_Algorithm.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_Core.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_ManagePool.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_OPenSsl.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_Client\XClient_APIHelp.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Client\XClient_Stream.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Client\XClient_Socket.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_NetHelp\NetHelp_XSocket.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_HelpComponents\HelpComponents_DataBase.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_HelpComponents\HelpComponents_XLog.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_RfcComponents\RfcComponents_HttpProtocol.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_RfcComponents\RfcComponents_NatProtocol.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_RfcComponents\RfcComponents_NTPProtocol.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_AVHelp.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_VideoCodec.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_AudioCodec.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_AVCollect.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_AVCodec\avcodec-60.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avdevice-60.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avfilter-9.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avformat-60.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\avutil-58.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\swresample-4.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\swscale-7.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\postproc-57.dll" "./"