copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_Algorithm.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_Core.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_ManagePool.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_OPenSsl.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_NetXApi.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\NetHelp_APIClient.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Client\XClient_Socket.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_DataBase.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_Packets.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_XLog.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_Authorize.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_RfcComponents\RfcComponents_HttpProtocol.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_AVCodec\XEngine_AVHelp.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\XEngine_VideoCodec.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\XEngine_AudioCodec.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\XEngine_AVCollect.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_StreamClient.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_HelpComponents\bson-1.0.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\mongoc-1.0.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\libmariadb.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\libpq.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\sqlite3.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\zlib1.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\plugin\caching_sha2_password.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\libcurl.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\nghttp2.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\libssl-3-x64.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\libcrypto-3-x64.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avcodec-59.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avdevice-59.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avfilter-8.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avformat-59.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avutil-57.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\swresample-4.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\swscale-6.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\postproc-56.dll" "./"