name: centos build workflows

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'XEngine_Source/**'
      - 'XEngine_Release/**'
      - '.github/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container:
      image: quay.io/centos/centos:${{ matrix.stream }}
      options: --platform ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            version: 9
            stream: stream9
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            version: 10
            stream: stream10
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            version: 9
            stream: stream9
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            version: 10
            stream: stream10

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine

      - name: sub module checkout (XEngine_OPenSource)
        uses: actions/checkout@v4
        with:
          repository: libxengine/XEngine_OPenSource
          path: XEngine_Source/XEngine_DependLibrary/XEngine_OPenSource
      - name: sub module checkout (XEngine_PhoneData)
        uses: actions/checkout@v4
        with:
          repository: libxengine/XEngine_PhoneData
          path: XEngine_Source/XEngine_DependLibrary/XEngine_PhoneData
      - name: sub module checkout (XEngine_IPMacData)
        uses: actions/checkout@v4
        with:
          repository: libxengine/XEngine_IPMacData
          path: XEngine_Source/XEngine_DependLibrary/XEngine_IPMacData

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
                  
      - name: install system package
        run: |
            dnf update -y
            dnf install gcc g++ make git jq unzip wget -y

      - name: install xengine library
        run: |
            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_RockyLinux_${{ matrix.version }}_${{ matrix.artifact }}.zip
            unzip ./XEngine_RockyLinux_${{ matrix.version }}_${{ matrix.artifact }}.zip -d ./XEngine_RockyLinux_${{ matrix.version }}_${{ matrix.artifact }}
            cd XEngine_RockyLinux_${{ matrix.version }}_${{ matrix.artifact }}
            
            chmod 777 *
            ./XEngine_LINEnv.sh -i 3
            
      - name: install build package
        run: |
            dnf install lua-devel opencv-devel qrencode-devel leptonica-devel tesseract-devel -y

      - name: make
        run: |
            cd XEngine_Source
            make
            make FLAGS=InstallAll
            make FLAGS=CleanAll

            make RELEASE=1
            make FLAGS=InstallAll
            make FLAGS=CleanAll
      - name: test
        run: |
            cd XEngine_Release
            chmod 777 copydb.sh
            ./copydb.sh
            ./XEngine_APIServiceApp -t

      - name: Upload folder as artifact with CentOS
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_MQServiceApp-CentOS_${{ matrix.version }}_${{ matrix.artifact }}
          path: XEngine_Release/
          retention-days: 1