name: macos build workflows

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'XEngine_Source/**'
      - 'XEngine_Release/**'
      - '.github/**'
  
permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
          - os: macos-14
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
        
       # 检出依赖的xengine仓库到指定的xengine目录
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine

      - name: sub module checkout (opensource)
        run: |
            git submodule init
            git submodule update
            
      - name: install library
        run: |
          brew install lua opencv qrencode
          ls -al /opt/homebrew/opt/opencv4
          ls -al /opt/homebrew/Cellar/opencv/4.10.0_15/include
          ls -al /opt/homebrew/Cellar/opencv/4.10.0_15/lib

     