name: C++ Build with Dependencies

#on: [push] # 触发条件，推送和拉取请求时，
on:
  workflow_dispatch:  # 添加这行来启用手动触发
  
permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x86]

    runs-on: windows-latest # 最新的 Windows 环境

    steps:
       # 检出您的主仓库代码
      - name: Checkout main repository code
        uses: actions/checkout@v3
        
       # 检出依赖的xengine仓库到指定的xengine目录
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v3
        with:
          repository: libxengine/xengine
          path: xengine

      - name: Checkout dependency repository (vcpkg)
        uses: actions/checkout@v3
        with:
          repository: https://github.com/microsoft/vcpkg.git
          path: vcpkg

      # 设置依赖库的环境变量
      - name: Set up Dependency Environment Variables
        run: |
          echo "XENGINE_INCLUDE=${{ github.workspace }}/xengine" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "XENGINE_LIB32=${{ github.workspace }}/xengine/XEngine_Windows/x86" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "XENGINE_LIB64=${{ github.workspace }}/xengine/XEngine_Windows/x64" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
        
      # 配置 MSBuild 的路径，准备构建 VC++ 项目
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      #编译
      - name: Build Solution
        run: msbuild XEngine_Source/XEngine.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}