name: windows build workflows

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'XEngine_Source/**'
      - 'XEngine_Release/**'
  
permissions:
  contents: read
  
jobs:
  build:
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        configuration: [Debug ,Release]
        platform: [x86 ,x64]

    runs-on: windows-latest # 最新的 Windows 环境

    steps:
       # 检出您的主仓库代码
      - name: Checkout main repository code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
        
       # 检出依赖的xengine仓库到指定的xengine目录
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine
          
      - name: sub module checkout (opensource)
        run: |
            git submodule init
            git submodule update
        shell: pwsh

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     
         
      - name: vcpkg install (x86)
        if: matrix.platform == 'x86'  
        run: |
            cd vcpkg
            ./bootstrap-vcpkg.bat
            ./vcpkg.exe install lua:x86-windows opencv[contrib]:x86-windows libqrencode:x86-windows
            ./vcpkg.exe integrate install
        shell: pwsh
      - name: vcpkg install (x64)
        if: matrix.platform == 'x64'  
        run: |
            cd vcpkg
            ./bootstrap-vcpkg.bat
            ./vcpkg.exe install lua:x64-windows opencv[contrib]:x64-windows libqrencode:x64-windows
            ./vcpkg.exe integrate install
        shell: pwsh

      # 设置依赖库的环境变量
      - name: Set up Dependency Environment Variables
        run: |
          echo "XENGINE_INCLUDE=${{ github.workspace }}/libxengine" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "XENGINE_LIB32=${{ github.workspace }}/libxengine/XEngine_Windows/x86" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "XENGINE_LIB64=${{ github.workspace }}/libxengine/XEngine_Windows/x64" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh
      - name: Set code page
        run: chcp 65001
        
      # 配置 MSBuild 的路径，准备构建 VC++ 项目
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      #编译
      - name: Build Solution
        run: msbuild XEngine_Source/XEngine.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:AdditionalOptions="/utf-8"
      #测试
      - name: Conditional Step for x86 Release
        if: matrix.configuration == 'Release' && matrix.platform == 'x86'
        run: |
          cp -r XEngine_Source/Release/*.dll XEngine_Release/
          cp -r XEngine_Source/Release/*.exe XEngine_Release/
          cp -r XEngine_Source/VSCopy_x86.bat XEngine_Release/
          cd XEngine_Release
          ./VSCopy_x86.bat
          ./XEngine_HttpApp.exe -t
        shell: pwsh
      - name: Conditional Step for x64 Release
        if: matrix.configuration == 'Release' && matrix.platform == 'x64'
        run: |
          cp -r XEngine_Source/x64/Release/*.dll XEngine_Release/
          cp -r XEngine_Source/x64/Release/*.exe XEngine_Release/
          cp -r XEngine_Source/VSCopy_x64.bat XEngine_Release/
          cd XEngine_Release
          ./VSCopy_x64.bat
        shell: pwsh

      - name: Upload folder as artifact with x86
        if: matrix.configuration == 'Release' && matrix.platform == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_HttpApp-x86_32-Windows
          path: XEngine_Release/
 
      - name: Upload folder as artifact with x64
        if: matrix.configuration == 'Release' && matrix.platform == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_HttpApp-x86_64-Windows
          path: XEngine_Release/